version: '3'
services:
  postgres:
    restart: always
    image: postgis/postgis:16-3.4
    volumes:
      - ./dbinit/:/docker-entrypoint-initdb.d/
      - ./data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=paris-transport-username
      - POSTGRES_PASSWORD=paris-transport-password
      - POSTGRES_DB=paris-transport-database
volumes:
  data:
